rootProject.name = 'java-basic'include 'stream'include 'thread'include 'connection'include 'java-doc'include 'serialization'include 'generic'include 'reflection'include 'reflection'include 'regex'include 'regex'include 'annotation'include 'lombok'include 'asynchronous'include 'asynchronousException'