sequenceDiagram    autonumber    participant Main as WeatherConsumerMain    participant Supplier as WeatherSupplier Supplier<U>    participant Consumer as WeatherConsumer Consumer<T>    Main->>Main: "Đang lấy thông tin thời tiết..."    Main->>Supplier: supplyAsync(new WeatherSupplier())    Main->>Main: "Tiếp tục làm việc khác..."    Supplier-->>Supplier: "Dữ liệu thời tiết..."    Supplier-->>Consumer: Trả về "Thời tiết..."    Consumer-->>Consumer: "Dữ liệu nhận được..."